version: "3.8"

services:
  # Serviço para desenvolvimento Next.js/React
  app:
    build:
      context: .
      target: development  # Usa o stage de desenvolvimento
      dockerfile: Dockerfile
    container_name: sea-pay-dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - HOST=0.0.0.0
    command: npm run dev
    restart: unless-stopped

  # Serviço para produção (opcional - para testar build de produção)
  app-prod:
    build:
      context: .
      target: runner  # Usa o stage de produção
      dockerfile: Dockerfile
    container_name: sea-pay-prod
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    profiles:
      - production  # Só inicia se especificar: docker-compose --profile production up